### ISSUE TITLE
Nancy SimpleAuthentication on Mono

### ISSUE THREAD

**Issue by oguzhantopcu** [SimpleAuthentication/SimpleAuthentication#139]
I have tested `SimpleAuthentication.Sample.NancyAuto` with xsp4.

But i have got these errors.

`Url: http://localhost:8080/authentication/redirect/facebook`

Error Details

```
Nancy.RequestExecutionException: Oh noes! ---> System.InvalidCastException: Cannot cast from source type to destination type.
  at System.Configuration.KeyValueConfigurationCollection.get_AllKeys () [0x00000] in :0 
  at SimpleAuthentication.Core.Config.ProviderConfigHelper.UseConfig (System.String sectionName) [0x00000] in :0 
  at SimpleAuthentication.Core.AuthenticationProviderFactory.<.cctor>b__c () [0x00000] in :0 
  at System.Lazy`1[SimpleAuthentication.Core.Config.Configuration].InitValue () [0x00000] in :0 
  --- End of inner exception stack trace ---
  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) [0x00000] in :0 
```

It works on .Net framework. It not works on mono environment.

**Comment by jjchiw** [comment]
I have the same problem and the "issue" is the implementation of [KeyValueConfigurationElement](https://github.com/mono/mono/blob/master/mcs/class/System.Configuration/System.Configuration/KeyValueConfigurationCollection.cs) when it tries to get `AllKeys`  the implementation in mono assume that `KeyValueConfigurationCollection` has a collection of `KeyValueConfigurationElement` [Line 62](https://github.com/mono/mono/blob/master/mcs/class/System.Configuration/System.Configuration/KeyValueConfigurationCollection.cs#L62)

So that's the cast that it's throwing the exception

```
Nancy.RequestExecutionException: Oh noes! ---> System.InvalidCastException: Cannot cast 
from source type to destination type.
```

So just to make it work changing the [ProviderConfigurationHelper Line 77](https://github.com/SimpleAuthentication/SimpleAuthentication/blob/master/Code/SimpleAuthentication.Core/Config/ProviderConfigurationHelper.cs#L77]) 

`Providers = (from p in configSection.Providers.AllKeys` 

to this 

`Providers = (from p in configSection.Providers.Cast<ProviderKey>().Select(x => x.Name)` 

it works...

Do you still accepts PR?

**Comment by PureKrome** [comment]
Yep. Sure do accept PR's.
