### ISSUE TITLE
Issue when calling functionality that leverages async/await in implementation of IAuthenticationCallbackProvider

### ISSUE THREAD

**Issue by Dashue** [SimpleAuthentication/SimpleAuthentication#163]
To set the scene:
In my IAuthenticationCallbackProvider in the method

``` csharp
public dynamic Process(NancyModule nancyModule, AuthenticateCallbackResult result)
{
    ...
    userRepository.Update(user).Wait();
    ...
}
```

The following repo works

``` csharp
public Task<User> Update(User user)
{
    var user= _store.GetByIdAsync<User>(id).Result;
    if (user== null)
    {
         user=new User();
    }
    else
    {
        user.LastLogin = DateTime.Now;
        user._rev = user._rev;
    }

    return _store.StoreAsync(user);
}
```

While this one just hangs

``` csharp
public async Task<User> Update(User user)
{
    var user= await _store.GetByIdAsync<User>(id);
    if (user== null)
    {
         user=new User();
    }
    else
    {
        user.LastLogin = DateTime.Now;
        user._rev = user._rev;
    }

    return await _store.StoreAsync(user);
}
```

**Comment by Dashue** [comment]
Perhaps introducing this would solve it and be of value?
`public async dynamic Process(NancyModule nancyModule, AuthenticateCallbackResult result)`

**Comment by PureKrome** [comment]
Hi @Dashue, thanks for the interest in the library.

About 8 odd months ago (eeks, that long, already?) I started a major refactor of the library to make it `async/await` happy.

[This is my fork + branch](https://github.com/PureKrome/SimpleAuthentication/tree/2.0-.net4.5/Code/SimpleAuthentication.Core), containing the massive update.

Now - the _exact_ class AND method you mentioned above has been _the_ most painful class to refactor ... only because I was at a huge mental-debate/anguish about wether to make it `async` or not.

Initially, i DID make it async because the work *I* do, is async (hence why I made the new branch and refactor). Then .. as I started using it more and _thinking_ about the developers who will also use this library, I started to wonder if they might not be all in this brave-new-async world.

So _currently_ my branch has the `Process` method as `sync`. (I reverted it back). My basis (so far) is this
- A person who knows `async` programming can probably handle downgrading their async to sync.
- A person who doesn't know `async` programming would probably have no idea how to call the `async` method in a sync context.

So I'd love a debate on this. Personally I'd prefer it to be `async` but I'm not sure it would work across the board.

thoughts anyone?

**Comment by Dashue** [comment]
I see your point with not forcing people to have to learn new things and I agree.
I realized that the issue I'm experiencing might automagically work if async, making task based work independent of async/await or not, should probably be the thing being investigated.

One option would be to provide another possible override: "ProcessAsync" removing the need to "figure out which way is the best/correct/has most usage".

As for your old branch, without knowing how much left there is of the tunnel until before you reach the light, perhaps it would be good to reset, restart and with your knowledge, try to partition the work into smaller defined pieces that anyone can chip away at independently and make baby steps towards the end result. Perhaps there's even work/task/features we can tackle in the 1.x version?

Thanks for taking time for input, I like the lib and plan on contributing where I can.
Cheers

**Comment by PureKrome** [comment]
Re: my branch, i'm already dogfooding the code -> it's about 95% there. I've been dogfooding my private RC's for a month+ now.

Hmm.. having 2 methods. that might work .. i'll need to see if that's a common thing or bad practice / code smell.

**Comment by Dashue** [comment]
Hah, i've been dogfooding my a hacked version of dev :D Probably with less success than you have with yours :)

**Comment by Dashue** [comment]
Few months down the line and I find myself in the same situation :) Where did we leave this last time?

**Comment by PureKrome** [comment]
I've basically stopped work on my v 2.0 async/await fork (and Simple Authentication overall) because of vNext. vNext have (was looks like) a nice Identity/Security repo which is basically doing what I've done. But most likely WAAAY better.

Once Beta 7 drops (which is targeting xplat) i'm going to give B7 a go (on my OSX) and see how their new identity/security stuff holds up. If it's nicely split up (like what I did in SA) then this repo can go bai bai and into maintenance mode for austerity.

**Comment by Dashue** [comment]
Hehe funny thing with my situation now is that the lib I'm using only supports async, hence I cannot save my user to db : D

What about us poor sods not able to upgrade to vNext? 

Is there much work needed to get a ProcessAsync Going?
Could I perhaps do it, or finish of the async/await work you started?

Cheers

**Comment by PureKrome** [comment]
> What about us poor sods not able to upgrade to vNext?

um ... i'm not sure really :disappointed: 

> Is there much work needed to get a ProcessAsync Going?
Um nope not at all!

>Could I perhaps do it, or finish of the async/await work you started?
Actually, I've done about 90-95% of the work already. I just have one deadlock issue which is the biggest problem (i think that's for auth'ing against a twitter account?). Basically, `async/await` in a sync environment totally destroyed me. Took _all_ the wind out of my sails. As/Aw is really simple to use and code against. I love it. .. ... _until_ ... i suddenly have a sync environment where I need to call some async code. _NOW_ i'm in hell as I can never get all this fucking _context switching bullshit_ to work and everything deadlocks and shit. 

Which was 50% why I gave up on my branch and the other 50% was because I noticed vNext seems to be doing it (the same concept of SA where I've broken up the process into nice lego pieces). Also, MS have a legion of people working/testing. This is just me (mostly).

So if you do want to help (which I would be forever appreciative)...

- Fork [_my_ repo] (https://github.com/PureKrome/SimpleAuthentication) (not the main repo).
- see what i've done in the *milestone/2.0* branch 
- play with the samples i've got in that branch
- try and use the dll's in your own code and see if there is anything that needs to be done.
- cry over my `async/await` code.

**Comment by Dashue** [comment]
For anyone else coming back (I've know I've done it a few times...) this is how I was able to solve it in the end. This allows for async/await implementation

Pattern
`Task.Run(async () => { /* use await as normal */ }).Wait();`

Working Example

    Task.Run(async () => {
        IAuthenticatedClient authClient = model.AuthenticatedClient;

        Identity identity = new Identity(authClient.ProviderName, authClient.UserInformation.Email, authClient.AccessToken.PublicToken, authClient.AccessToken.ExpiresOn);

        User existingUser = await _database.User(identity);

        if (existingUser != null)
        {
            await UpdateUser(existingUser, identity);
            signIn(existingUser);
        }
        else
        {
            User registeredUser = await RegisterUser(authClient.UserInformation, identity);
            signIn(registeredUser);
        }
    }).Wait();`
