### ISSUE TITLE
Feature Request: Generic OAuth Proviuder

### ISSUE THREAD

**Issue by ravensorb** [SimpleAuthentication/SimpleAuthentication#215]
Any thought to creating a generic oauth2 provider that is configured at runtime (config file or startup)

Ideally all that would be needed is
- Ability to set base redirect URL
- Ability to set auth path
- Ability to set user profile path
- Ability to enable/disable getting user profile automatically

Ex:
```
<add name="GenericOAuth2" key="" secret="" baseUrl="" authPath="" profilePath="" enableProfileLoading="false"  />
```

**Comment by PureKrome** [comment]
I've sorta tried this initially but there always sorta seemed to be some type of unique hitch, per provider.

We _do_ have some [config stuff here](https://github.com/SimpleAuthentication/SimpleAuthentication/tree/master/Code/SimpleAuthentication.Core/Config) for setting some stuff up in the `.config` file but that's still per provider specific.

To directly answer your question - *NO*. Why? Time (i don't have any bandwidth for this project any more) and because .NET Core has seceded this project IMO.

I do appreciate your time in posting an issue and asking a question :)

**Comment by ravensorb** [comment]
How has .net core seceded this project?

**Comment by PureKrome** [comment]
Oh my. _Totally_ wrong word to use. :blush:

"_Replaced_" was the word I really ment.
